### ISSUE TITLE
Can't open variable content

### ISSUE THREAD

**Issue by audiblespark** [lckr/jupyterlab-variableInspector#200]
You were showing that you can open the variables to inspect them further. This doesn't work for me. There is a magnifying glass icon, but it doesn't do anything. I can click anywhere, but nothing opens

**Comment by BlindB0** [comment]
Confirm.
Latest JupyterLab.
Ubuntu 20.10 x64

**Comment by lckr** [comment]
Hey guys, please make sure that the major version of the extension matches that of jupyter lab, e.g. jupyterlab >= 3.0.0 and extension >= 3.0.9.
If you did not install the extension via `pip` after the new jupyterlab release, you might have a version mismatch since the package on npm (used for the other installation possibilities) was outdated. This should be fixed now

**Comment by audiblespark** [comment]
I reinstalled via pip and it still doesn't work. I have the right version. Everything is up to date, but when I click on the magnifying glass only the circle next the Python 3 kernel is flashing up. Do you need a special kernel for this to work?

**Comment by lckr** [comment]
The inspection currently only works for some data types such a numpy array, pandas dataframes, ...
This of course means that you also need to have this packages installed.

**Comment by BlindB0** [comment]
Ubuntu 20.10 x64
lckr-jupyterlab-variableinspector was installed via 'sudo pip install lckr-jupyterlab-variableinspector'
version showed in pip 3.0.6
JupyterLab 3.0.13
Python kernel 3.8.6
Nodejs 12.18.2
Npm was not installed.
...
So I cannot see any content of variables with magnifying glass icon.
Not even list or dict variables, just flashing circle next the Python 3 kernel.

**Comment by coldspark29** [comment]
@lckr Why is this issue closed? It is not resolved. Of course I am using numpy arrays. It doesn't work.

**Comment by coldspark29** [comment]
@lckr Can you please reopen the issue?
